# имя контейнера
app-web:
  #докерфайл искать в указнной папке
  build: ./web
  # слушать по адресу 8081 то что в контейнере на 8080
  ports:
    - "8081:8080"
  # ссылается на другой контейнер
  links:
    - app-db

# имя контейнера
app-db:
  # докерфайл лежит тут
  build: ./db
  #слушать по адресу 5433 то что в контейнере на 5432
  ports:
    - "5433:5432"
  # подключить диски (разделы) с указанного контейнера
  volumes_from:
    - app-db-data
# название контейнера
# 2 контейнера постгре чтобы доке помнил данные
# данные и процесс постгре на разных контейнерах
app-db-data:
  # имя образа
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  # подключить раздел
  volumes:
    - /var/lib/postgresql/data